#
# Makefile for the Spica C++ unit test program.
#
# The main build is done from the SpicaCpp directory, but this Makefile is provided only to
# facilitate cleaning.
#

# Additional Rules
##################
clean:
	rm -f *.bc *.o *.s *.ll *~
