############################################################################
# FILE   : makefile
# AUTHOR : Peter Chapin <spicacality@kelseymountain.org>
#
# This is the makefile for the SpicaCpp project.
############################################################################

!include master.mif

.cpp:     ..\..
.cpp.obj: .AUTODEPEND
    wpp $(cpp_options) /ml /bt=dos $[*.cpp
